# Generated by Django 3.2.23 on 2023-11-06 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalSanctionsFallbackData',
            new_name='HistoricalSDNFallbackData',
        ),
        migrations.RenameModel(
            old_name='HistoricalSanctionsFallbackMetadata',
            new_name='HistoricalSDNFallbackMetadata',
        ),
        migrations.RenameModel(
            old_name='SanctionsFallbackData',
            new_name='SDNFallbackData',
        ),
        migrations.RenameModel(
            old_name='SanctionsFallbackMetadata',
            new_name='SDNFallbackMetadata',
        ),
        migrations.AlterModelOptions(
            name='historicalsdnfallbackdata',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sdn fallback data'},
        ),
        migrations.AlterModelOptions(
            name='historicalsdnfallbackmetadata',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sdn fallback metadata'},
        ),
        migrations.RenameField(
            model_name='historicalsdnfallbackdata',
            old_name='sanctions_fallback_metadata',
            new_name='sdn_fallback_metadata',
        ),
        migrations.RenameField(
            model_name='sdnfallbackdata',
            old_name='sanctions_fallback_metadata',
            new_name='sdn_fallback_metadata',
        ),
    ]
